# Generated by Django 5.2.8 on 2025-12-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
